server:
  port: 8080

spring:
  application:
    name: gateway-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        service: gateway-service
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: feature-optimization-service
          uri: lb://feature-optimization-service
          predicates:
            - Path=/api/feature-optimization/**
          filters:
            - StripPrefix=1
        - id: model-building-service
          uri: lb://model-building-service
          predicates:
            - Path=/api/model-building/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true