server:
  port: 10010

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        service: gateway-service
    gateway:
      routes:
        - id: feature-optimization-service
          uri: lb://feature-optimization-service
          predicates:
            - Path=/feature-optimization-dataset/**