server:
  port: 10010

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        service: gateway-service
    gateway:
      routes:
        - id: feature-optimization-service
          uri: lb://feature-optimization-service
          predicates:
            - Path=/feature-optimization-dataset/**
        - id: model-building-service
          uri: lb://model-building-service
          predicates:
            - Path=/model-building-dataset/**
        - id: data-management-service
          uri: lb://data-management-service
          predicates:
            - Path=/spatial-dataset/**
        - id: preprocessing-service
          uri: lb://preprocessing-service
          predicates:
            - Path=/preprocessing/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"