server:
  port: 8080

spring:
  application:
    name: gateway-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: feature-optimization-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/feature-optimization/**
          filters:
            - RewritePath=/api/feature-optimization/(?<segment>.*), /feature-optimization-dataset/$\{segment}
        - id: model-building-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/model-building/**
          filters:
            - RewritePath=/api/model-building/(?<segment>.*), /model-building-dataset/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug