server:
  port: 10030

spring:
  application:
    name: preprocessing-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pestfcst?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: preprocessing-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 预处理相关配置
preprocessing:
  temp-dir: D:/temp/pestfcst/preprocessing
  output-dir: D:/temp/pestfcst/output
  processing-methods:
    - name: data-cleaning
      enabled: true
    - name: spatial-point-extraction
      enabled: true
    - name: normalization
      enabled: true 